dev-lang/spidermonkey: Fix missing symbols sys-auth/polkit fails to build with "undefined reference to `void js::UnsafeTraceManuallyBarrieredEdge<JS::Value>(JSTracer*, JS::Value*, char const*)'" error if dev-lang/spidermonkey is compiled with clang references: https://bugs.gentoo.org/681656 https://bugzilla.mozilla.org/show_bug.cgi?id=1426865